config/routes.rb
Rails.application.routes.draw do
  resources :hostels
resources :hotel
resources :users
resources :books
resources :products
resources :animals
root 'animals#index'
 # aFor details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
	has_many :products
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def index
  	@users  =User.all
    @books = Book.all
    @products = Product.all
  end
  def edit
  	@user = User.find(params[:id])

  end

  def show
  	@user = User.find(params[:id])
  	@user_books = @user.books
    @user_products = @user.products
  end

  def create
  	@user = User.new(user_params)
  	@user.save
  	redirect_to users_path
  end

  def new
  	@user = User.new
  end

  def update
  	@user = User.find(params[:id])
  	@user = @user.update(user_params)
  	redirect_to users_path

  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to users_path
  end
  
   private

   def user_params
   	params.require(:user).permit(:name,:city,:country,:email)
   	
   end


end

app/views/users/edit.html.erb
<h1> creating new user</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city%>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
   <div class="field">
    <%= f.label :email%>
    <%= f.text_field :email%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to  "users list", users_path %>
<%= link_to  "back", users_path %>

app/views/users/index.html.erb
<h1> users index </h1>
<table>
	<thead>
		<tr>
			<th> Name</th>
			<th> Cite</th>
			<th> Country</th>
			<th> Email</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%=user.name%></td>
			<td><%=user.city%></td>
			<td><%=user.country%></td>
			<td><%=user.email%></td>
			<td><%colspan= '3'%></td>

			<td><%=link_to 'show', user_path(user)%></td>
			<td><%=link_to 'edit', edit_user_path(user)%></td>
			<td><%=link_to 'destroy', user,method: :delete,data:{confirm: 'Are you sure'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "New user" ,new_user_path%>

<br>
<br>

<h1> books index </h1>
<table>
	<thead>
		<tr>
			<th> Name</th>
			<th> description</th>
			<th>user id</th>
			<td><%colspan= '3'%></td>	
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.name %></td>
			<td><%= book.description %></td>
			<td><%= book.user_id %></td>
			<td><%=link_to 'show', book_path(book)%></td>
			<td><%=link_to 'edit', edit_book_path(book)%></td>
			<td><%=link_to 'destroy', book,method: :delete,data:{confirm: 'Are you sure'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "New book" ,new_book_path%>

<br>
<br>

<h1> products index </h1>
<table>
	<thead>
		<tr>
			<th> Name</th>
			<th> description</th>
			<th>user id</th>	
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%=product.name%></td>
			<td><%=product.description%></td>
			<td><%=product.user_id%></td>
			
			<td><%colspan= '3'%></td>

			<td><%=link_to 'show', product_path(product)%></td>
			<td><%=link_to 'edit', edit_product_path(product)%></td>
			<td><%=link_to 'destroy', product,method: :delete,data:{confirm: 'Are you sure'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>
  
  <%= link_to "New product",new_product_path%>       

app/views/users/new.html.erb
<h1> creating new user</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city%>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
   <div class="field">
    <%= f.label :email%>
    <%= f.text_field :email%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to  "users list", users_path %>

app/views/users/show.html.erb
<h1> details </h1>
 <p> Name : <%= @user.name %> </p>
 <p> city :<%= @user.city %></p>
 <p> country :<%= @user.country%></p>
 <p>email :<%= @user.email%></p>
 <h1> user books </h1>
<table>
	<thead>
		<tr>
			<th> Name</th>
			<th> description</th>
			<th>user id</th>
			<td><%colspan= '3'%></td>	
		</tr>
	</thead>
	<tbody>
		<% @user_books.each do |book| %>
		<tr>
			<td><%=book.name%></td>
			<td><%=book.description%></td>
		     <td><%=book.user_id%></td>
			<td><%=link_to 'show', book_path(book)%></td>
			<td><%=link_to 'edit', edit_book_path(book)%></td>
			<td><%=link_to 'destroy', book,method: :delete,data:{confirm: 'Are you sure'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<h1> user products </h1>
<table>
	<thead>
		<tr>
			<th> Name</th>
			<th> description</th>
			<th>user id</th>
			<td><%colspan= '3'%></td>	
		</tr>
	</thead>
	<tbody>
		<% @user_products.each do |product| %>
		<tr>
			<td><%=product.name%></td>
			<td><%=product.description%></td>
			<td><%=product.user_id%></td>
			<td><%=link_to 'show', product_path(product)%></td>
			<td><%=link_to 'edit', edit_product_path(product)%></td>
			<td><%=link_to 'destroy', product,method: :delete,data:{confirm: 'Are you sure'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>

 <p> <%= link_to "back",users_path %></p>
 <p> <%= link_to "create user" ,new_user_path %></p>
 <p> <%= link_to "edit user" ,new_user_path %></p>