config/routes.rb
Rails.application.routes.draw do
  resources :hostels
resources :hotel
resources :users
resources :books
resources :products
resources :animals
root 'animals#index'
 # aFor details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hostel.rb
class Hostel < ApplicationRecord
end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController
  before_action :set_hostel, only: [:show, :edit, :update, :destroy]

  # GET /hostels
  # GET /hostels.json
  def index
    @hostels = Hostel.all
  end

  # GET /hostels/1
  # GET /hostels/1.json
  def show
  end

  # GET /hostels/new
  def new
    @hostel = Hostel.new
  end

  # GET /hostels/1/edit
  def edit
  end

  # POST /hostels
  # POST /hostels.json
  def create
    @hostel = Hostel.new(hostel_params)
    respond_to do |format|
      if @hostel.save
        format.html { redirect_to @hostel, notice: 'Hostel was successfully created.' }
        format.json { render :show, status: :created, location: @hostel }
      else
        format.html { render :new }
        format.json { render json: @hostel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hostels/1
  # PATCH/PUT /hostels/1.json
  def update
    respond_to do |format|
      if @hostel.update(hostel_params)
        format.html { redirect_to @hostel, notice: 'Hostel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hostel }
      else
        format.html { render :edit }
        format.json { render json: @hostel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostels/1
  # DELETE /hostels/1.json
  def destroy
    @hostel.destroy
    respond_to do |format|
      format.html { redirect_to hostels_url, notice: 'Hostel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostel
      @hostel = Hostel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostel_params
      params.require(:hostel).permit(:product_id, :product_description, :product_name)
    end
end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/views/hostels/_form.html.erb
<%= form_for(hostel) do |f| %>
  <% if hostel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hostel.errors.count, "error") %> prohibited this hostel from being saved:</h2>

      <ul>
      <% hostel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :product_description %>
    <%= f.text_field :product_description %>
  </div>

  <div class="field">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hostels/edit.html.erb
<h1>Editing Hostel</h1>

<%= render 'form', hostel: @hostel %>

<%= link_to 'Show', @hostel %> |
<%= link_to 'Back', hostels_path %>

app/views/hostels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hostels</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Product description</th>
      <th>Product name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hostels.each do |hostel| %>
      <tr>
        <td><%= hostel.product_id %></td>
        <td><%= hostel.product_description %></td>
        <td><%= hostel.product_name %></td>
        <td><%= link_to 'Show', hostel %></td>
        <td><%= link_to 'Edit', edit_hostel_path(hostel) %></td>
        <td><%= link_to 'Destroy', hostel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Hostel', new_hostel_path %>

app/views/hostels/new.html.erb
<h1>New Hostel</h1>

<%= render 'form', hostel: @hostel %>

<%= link_to 'Back', hostels_path %>

app/views/hostels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @hostel.product_id %>
</p>

<p>
  <strong>Product description:</strong>
  <%= @hostel.product_description %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @hostel.product_name %>
</p>

<%= link_to 'Edit', edit_hostel_path(@hostel) %> |
<%= link_to 'Back', hostels_path %>